# Generated by Django 3.0.4 on 2020-03-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
